/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-namespace */
/**
 * Schema types formerly generated by Prisma, now defined locally so the app
 * runs with zero database dependency. The runtime store in `src/lib/db.ts`
 * implements the same `db` query API against in-memory collections.
 */

// ============ ENUMS ============

export const RoleValues = ["STUDENT", "TEACHER", "RESEARCHER", "ADMIN"] as const;
export type Role = (typeof RoleValues)[number];

export const AdminRoleValues = [
  "SUPER_ADMIN",
  "USER_MANAGER",
  "CONTENT_MODERATOR",
  "PAYMENT_MANAGER",
  "VERIFICATION_MANAGER",
  "SUPPORT_ADMIN",
] as const;
export type AdminRole = (typeof AdminRoleValues)[number];

export const UserStatusValues = ["ACTIVE", "SUSPENDED", "DISABLED", "PENDING_VERIFICATION"] as const;
export type UserStatus = (typeof UserStatusValues)[number];

export const VerificationStatusValues = ["NONE", "PENDING", "VERIFIED", "REJECTED"] as const;
export type VerificationStatus = (typeof VerificationStatusValues)[number];

export const PaperStatusValues = [
  "DRAFT",
  "PENDING_REVIEW",
  "APPROVED",
  "REJECTED",
  "REQUEST_CHANGES",
  "REMOVED",
  "SUSPENDED",
] as const;
export type PaperStatus = (typeof PaperStatusValues)[number];

export const AccessTypeValues = ["FREE", "PAID", "EXTERNAL_LINK"] as const;
export type AccessType = (typeof AccessTypeValues)[number];

export const PermissionStatusValues = [
  "PENDING",
  "APPROVED",
  "REJECTED",
  "REVOKED",
  "EXPIRED",
  "REQUEST_CHANGES",
] as const;
export type PermissionStatus = (typeof PermissionStatusValues)[number];

export const PaymentStatusValues = ["PENDING", "SUCCESSFUL", "FAILED", "REFUNDED", "CANCELLED"] as const;
export type PaymentStatus = (typeof PaymentStatusValues)[number];

export const CallRequestStatusValues = [
  "PENDING",
  "ACCEPTED",
  "REJECTED",
  "RESCHEDULED",
  "COMPLETED",
  "CANCELLED",
] as const;
export type CallRequestStatus = (typeof CallRequestStatusValues)[number];

export const CollaborationStatusValues = ["OPEN", "CLOSED", "FILLED"] as const;
export type CollaborationStatus = (typeof CollaborationStatusValues)[number];

export const CollaborationRequestStatusValues = ["PENDING", "ACCEPTED", "REJECTED", "CANCELLED"] as const;
export type CollaborationRequestStatus = (typeof CollaborationRequestStatusValues)[number];

export const ReportStatusValues = ["OPEN", "INVESTIGATING", "RESOLVED", "DISMISSED"] as const;
export type ReportStatus = (typeof ReportStatusValues)[number];

export const ReportCategoryValues = [
  "COPYRIGHT",
  "INCORRECT_INFO",
  "SPAM",
  "HARASSMENT",
  "FRAUD",
  "INAPPROPRIATE_CONTENT",
  "OTHER",
] as const;
export type ReportCategory = (typeof ReportCategoryValues)[number];

export const NotificationPriorityValues = ["LOW", "MEDIUM", "HIGH"] as const;
export type NotificationPriority = (typeof NotificationPriorityValues)[number];

export const RefundStatusValues = ["PENDING", "PROCESSED", "FAILED"] as const;
export type RefundStatus = (typeof RefundStatusValues)[number];

// ============ MODEL INTERFACES ============
// Used where the code used to import Prisma model types. relation fields are
// allowed via the index signature so that `include` results type-check.

export interface User {
  id: string;
  name: string;
  email: string;
  emailVerified: Date | null;
  passwordHash: string;
  role: Role;
  adminRole: AdminRole | null;
  status: UserStatus;
  verificationStatus: VerificationStatus;
  avatarUrl: string | null;
  bio: string | null;
  location: string | null;
  phone: string | null;
  title: string | null;
  designation: string | null;
  departmentId: string | null;
  createdAt: Date;
  updatedAt: Date;
  lastActiveAt: Date | null;
  isDemo: boolean;
  isSeed: boolean;
  [key: string]: any;
}

export interface Profile {
  id: string;
  userId: string;
  phone: string | null;
  website: string | null;
  country: string | null;
  city: string | null;
  address: string | null;
  headline: string | null;
  bio: string | null;
  skills: string | null;
  profileCompletion: number;
  views: number;
  aboutUs: string | null;
  createdAt: Date;
  updatedAt: Date;
  [key: string]: any;
}

export interface ResearcherProfile {
  id: string;
  userId: string;
  universityId: string | null;
  departmentId: string | null;
  designation: string | null;
  experienceYears: number | null;
  bio: string | null;
  researchFocus: string | null;
  citations: number;
  publications: number;
  verified: boolean;
  whatsappNumber: string | null;
  createdAt: Date;
  updatedAt: Date;
  [key: string]: any;
}

export interface ResearchPaper {
  id: string;
  title: string;
  slug: string;
  abstract: string;
  keywords: string | null;
  researchField: string | null;
  publicationType: string | null;
  journal: string | null;
  conference: string | null;
  publisher: string | null;
  publicationDate: Date | null;
  doi: string | null;
  volume: string | null;
  issue: string | null;
  pages: string | null;
  citations: number;
  externalUrl: string | null;
  pdfUrl: string | null;
  coverImageUrl: string | null;
  fileAssetId: string | null;
  price: number | null;
  currency: string;
  accessType: AccessType;
  status: PaperStatus;
  views: number;
  rejectionReason: string | null;
  licenseType: string | null;
  needsPermission: boolean;
  isAuthorized: boolean;
  categoryId: string | null;
  uploaderId: string;
  universityId: string | null;
  createdAt: Date;
  updatedAt: Date;
  [key: string]: any;
}

export interface University {
  id: string;
  name: string;
  slug: string;
  logoUrl: string | null;
  description: string | null;
  website: string | null;
  country: string | null;
  city: string | null;
  address: string | null;
  verified: boolean;
  createdAt: Date;
  updatedAt: Date;
  isSeed: boolean;
  [key: string]: any;
}

export interface ResearchArea {
  id: string;
  name: string;
  slug: string;
  description: string | null;
  icon: string | null;
  color: string | null;
  createdAt: Date;
  isSeed: boolean;
  [key: string]: any;
}

export interface PaperAuthor {
  id: string;
  paperId: string;
  userId: string | null;
  name: string;
  email: string | null;
  affiliation: string | null;
  isPrimary: boolean;
  order: number;
  createdAt: Date;
  [key: string]: any;
}

// Namespace mirroring `Prisma.*` types used by API routes / server pages.
export namespace Prisma {
  export type ResearchPaperWhereInput = Record<string, any>;
  export type UserWhereInput = Record<string, any>;
}

// Rows returned by the in-memory store are loosely shaped; used for map()
// callbacks over included relations where a concrete interface is irrelevant.
export type DbRow = Record<string, any>;